apiVersion: apps/v1
kind: Deployment
metadata:
  name: clo835-a2-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: clo835-a2-app
  template:
    metadata:
      labels:
        app: clo835-a2-app
    spec:
      containers:
        - name: clo835-a2-container
          #Tried to implement a Template pattern but it was not working, so I just hardcoded the image version to 0.3
          image: elvistrann7/clo835-assignment2:0.3
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10