apiVersion: apps/v1
kind: Deployment
metadata:
  name: clo835-a2-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: clo835-a2-app
  template:
    metadata:
      labels:
        app: clo835-a2-app
    spec:
      containers:
        - name: clo835-a2-container
          #Template Pattern, will be filled at runtime with the value of DOCKERHUB_USERNAME secret
          image: ${DOCKERHUB_USERNAME}/clo835-assignment2:0.2
          ports:
            - containerPort: 8080
          #The path name comes from the Program.cs file
          livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          #The path name comes from the Program.cs file
          readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10